name: kubeconfig
description: Kubeconfig utility library for Javascript and Dart. Validate, convert, or merge kubeconfig files.
version: 1.0.0+1
repository: https://github.com/fatihsever/kubeconfig-lib
issue_tracker: https://github.com/fatihsever/kubeconfig-lib/issues
documentation: https://kubeconfig-lib.pages.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.11.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  copy_with_extension_gen: ^5.0.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  test: ^1.25.1
  very_good_analysis: ^5.1.0

screenshots:
  - description: Kubeconfig logo
    path: assets/logo.webp
